version: 2
general:
  build_dir: build
jobs:
  build:
    docker:
      - image: circleci/classic:latest
    steps:
      - checkout
      - run: 
        name: Configure Build
        command: 'cmake ..'
      -run:
        name: Build
        command: make
  test:
    docker:
      - image: circleci/classic:latest
    steps:
      -run: 
        name: Test
        command: 'make test'
workflows:
  version: 2
  build_and_test:
    jobs: 
      -build
