version: 2
general:
  build_dir: build
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: 
        command: 'cmake ..'
      -run:
        command: make
  test:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      -run: 
        command: 'make test'
        
