version: 2
general:
  build_dir: build
jobs:
  build:
    machine:
      - image: circleci/classic:201708-01
    steps:
      - checkout
      - run: 
        - name: Install cmake
        - command: 'sudo apt-get install cmake'
      - run: 
        - name: Config CMake
        - command: 'cmake ..'
