version: 2
general:
  build_dir: build
jobs:
  build:
    docker:
      - image: circleci/classic:default
    steps:
      - command: sudo apt-get install cmake
      - checkout
      - run: 'cmake ..'
